<a href="https://colab.research.google.com/github/arch1781993/Learning_Pytorch_DeepLearning/blob/main/1_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors
 (Documented on pytorch tensors)
- A torch.Tensor is a multi-dimensional matrix containing elements of a single data type
- Similar to numpy arrays, but full of fun things that make them work better on GPU (vs regular CPU)
- default data type : float32
- More suitable for deep learning than numpy array

In [2]:
import torch
import numpy as np

# Python Lists

In [3]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [9]:
my_list2 = [[1,2,3,4,5],[1,2,3,4,5]] # multi-dimensional list
my_list2

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

# Numpy Arrays

In [10]:
np1 = np.random.rand(3,4)
np1

array([[0.10049078, 0.2988062 , 0.19364508, 0.69351566],
       [0.20521809, 0.62285322, 0.85263033, 0.26450289],
       [0.77949018, 0.99719754, 0.34033214, 0.6139271 ]])

In [11]:
np1.dtype

dtype('float64')

# Tensors

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.5285,  1.7815, -0.1118, -0.6109],
        [ 0.0454, -0.5977, -0.6478, -0.5093],
        [ 2.1865,  0.7775,  0.6955,  0.7432]])

In [21]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d
# tensor_3d.dtype   # data type is float 32

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

## Create tensor out of numpy arrays

In [18]:
my_tensor = torch.tensor(np1)
my_tensor                   # my_tensor data type is float64, because the data type of numpy array was float 64

tensor([[0.1005, 0.2988, 0.1936, 0.6935],
        [0.2052, 0.6229, 0.8526, 0.2645],
        [0.7795, 0.9972, 0.3403, 0.6139]], dtype=torch.float64)