<a href="https://colab.research.google.com/github/arch1781993/Learning_Pytorch_DeepLearning/blob/main/2_Tensor_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
my_tensor = torch.arange(10)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape and View

In [6]:
my_tensor = my_tensor.reshape(2,5)
my_tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
# Reshaping if we dont know the number of items using -1. lot of times when data is huge we dont know how many items are there.
my_tensor2 = torch.arange(10)
my_tensor2 = my_tensor2.reshape(2,-1)
my_tensor2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
my_tensor2 = my_tensor2.reshape(-1,2)
my_tensor2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [13]:
# ReshaPING WITH view
my_tensor3 = torch.arange(10)
my_tensor4 = my_tensor3.view(2,5)
my_tensor4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
# CHeck out the differences between reshape and view

In [15]:
# With reshape and view, the subsidiary tensors will update automatically if you update the base tensor
my_tensor5 = torch.arange(10)
my_tensor6 = my_tensor5.reshape(2,5)
my_tensor6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# lets update my_tensor5
my_tensor5[1] = 3212
my_tensor5

tensor([   0, 3212,    2,    3,    4,    5,    6,    7,    8,    9])

In [18]:
my_tensor6

tensor([[   0, 3212,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

# Slices

In [19]:
my_tensor7 = torch.arange(10)
my_tensor7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# Grabing an specific item
my_tensor7[7]            # Note: it is not a number, it is a tensor, think of it as a scalar tensor

tensor(7)

In [22]:
my_tensor8 = my_tensor7.reshape(5,2)
my_tensor8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [24]:
# Grabing a slice
my_tensor8[:,1]       # this returns a 1d kind of a list

tensor([1, 3, 5, 7, 9])

In [26]:
# what if we want to keep the column strucutre
my_tensor8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])