<a href="https://colab.research.google.com/github/arch1781993/Learning_Pytorch_DeepLearning/blob/main/3_Tensor_Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor math operations
- Add, Subtract,Multiply, Divide, Remainder, Exponent
- Shorthand and Longhand
- Reassignment

In [1]:
import torch
import numpy as np

In [25]:
a = torch.tensor([1,2,3,4])
b = torch.tensor([5,6,7,8])

In [4]:
# Addition (Shorthand)
a+b

tensor([ 6,  8, 10, 12])

In [7]:
# Addition (Longhand)
torch.add(a,b)                    # shorthand, longhand both are same.

tensor([ 6,  8, 10, 12])

In [8]:
# Subtractions (Shorthand)
b-a

tensor([4, 4, 4, 4])

In [9]:
# Subtraction (Longhand)
torch.sub(b,a)

tensor([4, 4, 4, 4])

In [10]:
# Multiplication (Shorthand)
a*b

tensor([ 5, 12, 21, 32])

In [11]:
# Multiplication (Longhand)
torch.mul(a,b)

tensor([ 5, 12, 21, 32])

In [12]:
# Division (Shorthand)
b/a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
# Division (Longhand)
torch.div(b,a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
# Remainder (Shorthand)
b%a

tensor([0, 0, 1, 0])

In [15]:
# Remainder (Longhand)
torch.remainder(b,a)

tensor([0, 0, 1, 0])

In [16]:
# Exponent/Power (Longhand)
torch.pow(a,b)

tensor([    1,    64,  2187, 65536])

In [22]:
# For all mathematical operations (Another way to write Longhand)
a.add(b)
b.sub(a)
b.mul(a)
b.div(a)
b.remainder(a)
a.pow(b)

tensor([    1,    64,  2187, 65536])

## Reassignment
- add an ( _ ) after the operation symbol (for longhand)

In [23]:
# Shorthand
# a = a+b

In [28]:
# Longhand
a.add_(b)

tensor([ 6,  8, 10, 12])

In [29]:
a

tensor([ 6,  8, 10, 12])